package main

import (
	"fmt"

	"github.com/gocnn/spark/tensor"
)

func maxAbsDiff(a, b []float32) float32 {
	m := float32(0)
	for i := range a {
		d := a[i] - b[i]
		if d < 0 {
			d = -d
		}
		if d > m {
			m = d
		}
	}
	return m
}

func main() {
	// Load input generated by relu/main.py
	x := tensor.MustReadNPY[float32]("x.npy") // [B,C,H,W]
	x.SetIsVar(true)

	// ReLU: y = max(x, 0)
	zero, err := tensor.Zeros[float32](x.Shape(), x.Device())
	if err != nil {
		panic(err)
	}
	y, err := x.Maximum(zero)
	if err != nil {
		panic(err)
	}

	// Loss = sum(y)
	loss := y.MustSumAll()

	// Backward
	gs := loss.MustBackward()
	dx := gs.Get(x)

	// Load references
	yRef := tensor.MustReadNPY[float32]("y_ref.npy")
	dxRef := tensor.MustReadNPY[float32]("dx_ref.npy")

	fmt.Printf("y shape: %v, yRef shape: %v\n", y.Shape().Dims(), yRef.Shape().Dims())
	fmt.Printf("max_abs_diff y: %.6g\n", maxAbsDiff(y.Data(), yRef.Data()))
	fmt.Printf("dx shape: %v, dxRef shape: %v\n", dx.Shape().Dims(), dxRef.Shape().Dims())
	fmt.Printf("max_abs_diff dx: %.6g\n", maxAbsDiff(dx.Data(), dxRef.Data()))
}
