//go:build windows

package flashattn

//go:generate cmd /c if not exist build mkdir build
//go:generate cmd /c if not exist lib mkdir lib
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_api.cu -o build/flash_api.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim128_fp16_sm80.cu -o build/flash_fwd_hdim128_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim160_fp16_sm80.cu -o build/flash_fwd_hdim160_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim192_fp16_sm80.cu -o build/flash_fwd_hdim192_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim224_fp16_sm80.cu -o build/flash_fwd_hdim224_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim256_fp16_sm80.cu -o build/flash_fwd_hdim256_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim32_fp16_sm80.cu -o build/flash_fwd_hdim32_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim64_fp16_sm80.cu -o build/flash_fwd_hdim64_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim96_fp16_sm80.cu -o build/flash_fwd_hdim96_fp16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim128_bf16_sm80.cu -o build/flash_fwd_hdim128_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim160_bf16_sm80.cu -o build/flash_fwd_hdim160_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim192_bf16_sm80.cu -o build/flash_fwd_hdim192_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim224_bf16_sm80.cu -o build/flash_fwd_hdim224_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim256_bf16_sm80.cu -o build/flash_fwd_hdim256_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim32_bf16_sm80.cu -o build/flash_fwd_hdim32_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim64_bf16_sm80.cu -o build/flash_fwd_hdim64_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim96_bf16_sm80.cu -o build/flash_fwd_hdim96_bf16_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim128_fp16_causal_sm80.cu -o build/flash_fwd_hdim128_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim160_fp16_causal_sm80.cu -o build/flash_fwd_hdim160_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim192_fp16_causal_sm80.cu -o build/flash_fwd_hdim192_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim224_fp16_causal_sm80.cu -o build/flash_fwd_hdim224_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim256_fp16_causal_sm80.cu -o build/flash_fwd_hdim256_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim32_fp16_causal_sm80.cu -o build/flash_fwd_hdim32_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim64_fp16_causal_sm80.cu -o build/flash_fwd_hdim64_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim96_fp16_causal_sm80.cu -o build/flash_fwd_hdim96_fp16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim128_bf16_causal_sm80.cu -o build/flash_fwd_hdim128_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim160_bf16_causal_sm80.cu -o build/flash_fwd_hdim160_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim192_bf16_causal_sm80.cu -o build/flash_fwd_hdim192_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim224_bf16_causal_sm80.cu -o build/flash_fwd_hdim224_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim256_bf16_causal_sm80.cu -o build/flash_fwd_hdim256_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim32_bf16_causal_sm80.cu -o build/flash_fwd_hdim32_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim64_bf16_causal_sm80.cu -o build/flash_fwd_hdim64_bf16_causal_sm80.obj
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -D_USE_MATH_DEFINES -c kernels/flash_fwd_hdim96_bf16_causal_sm80.cu -o build/flash_fwd_hdim96_bf16_causal_sm80.obj
//go:generate lib /OUT:build\flashattention.lib build\*.obj
//go:generate cmd /c copy build\flashattention.lib lib
