//go:build linux

package flashattn

//go:generate mkdir -p build
//go:generate mkdir -p lib
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_api.cu -o build/flash_api.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim128_fp16_sm80.cu -o build/flash_fwd_hdim128_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim160_fp16_sm80.cu -o build/flash_fwd_hdim160_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim192_fp16_sm80.cu -o build/flash_fwd_hdim192_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim224_fp16_sm80.cu -o build/flash_fwd_hdim224_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim256_fp16_sm80.cu -o build/flash_fwd_hdim256_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim32_fp16_sm80.cu -o build/flash_fwd_hdim32_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim64_fp16_sm80.cu -o build/flash_fwd_hdim64_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim96_fp16_sm80.cu -o build/flash_fwd_hdim96_fp16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim128_bf16_sm80.cu -o build/flash_fwd_hdim128_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim160_bf16_sm80.cu -o build/flash_fwd_hdim160_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim192_bf16_sm80.cu -o build/flash_fwd_hdim192_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim224_bf16_sm80.cu -o build/flash_fwd_hdim224_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim256_bf16_sm80.cu -o build/flash_fwd_hdim256_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim32_bf16_sm80.cu -o build/flash_fwd_hdim32_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim64_bf16_sm80.cu -o build/flash_fwd_hdim64_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim96_bf16_sm80.cu -o build/flash_fwd_hdim96_bf16_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim128_fp16_causal_sm80.cu -o build/flash_fwd_hdim128_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim160_fp16_causal_sm80.cu -o build/flash_fwd_hdim160_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim192_fp16_causal_sm80.cu -o build/flash_fwd_hdim192_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim224_fp16_causal_sm80.cu -o build/flash_fwd_hdim224_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim256_fp16_causal_sm80.cu -o build/flash_fwd_hdim256_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim32_fp16_causal_sm80.cu -o build/flash_fwd_hdim32_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim64_fp16_causal_sm80.cu -o build/flash_fwd_hdim64_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim96_fp16_causal_sm80.cu -o build/flash_fwd_hdim96_fp16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim128_bf16_causal_sm80.cu -o build/flash_fwd_hdim128_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim160_bf16_causal_sm80.cu -o build/flash_fwd_hdim160_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim192_bf16_causal_sm80.cu -o build/flash_fwd_hdim192_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim224_bf16_causal_sm80.cu -o build/flash_fwd_hdim224_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim256_bf16_causal_sm80.cu -o build/flash_fwd_hdim256_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim32_bf16_causal_sm80.cu -o build/flash_fwd_hdim32_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim64_bf16_causal_sm80.cu -o build/flash_fwd_hdim64_bf16_causal_sm80.o
//go:generate nvcc -std=c++17 -O3 -arch=sm_80 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -Icutlass/include --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --verbose -Xcompiler -fPIC -c kernels/flash_fwd_hdim96_bf16_causal_sm80.cu -o build/flash_fwd_hdim96_bf16_causal_sm80.o
//go:generate ar rcs build/libflashattention.a build/*.o
//go:generate cp build/libflashattention.a lib/
