package main

import (
	"fmt"

	"github.com/gocnn/spark/tensor"
)

func maxAbsDiff(a, b []float32) float32 {
	m := float32(0)
	for i := range a {
		d := a[i] - b[i]
		if d < 0 {
			d = -d
		}
		if d > m {
			m = d
		}
	}
	return m
}

func main() {
	// Load input generated by maxpool/main.py
	x := tensor.MustReadNPY[float32]("x.npy") // [B,C,H,W]
	x.SetIsVar(true)

	// Forward: y = MaxPool2d(x, k=2x2, s=2x2)
	y := x.MustMaxPool2d(2, 2, 2, 2)

	// Loss = sum(y)
	loss := y.MustSumAll()

	// Backward
	gs := loss.MustBackward()
	dx := gs.Get(x)

	// Load references
	yRef := tensor.MustReadNPY[float32]("y_ref.npy")
	dxRef := tensor.MustReadNPY[float32]("dx_ref.npy")

	if y == nil {
		fmt.Println("y is nil")
	} else {
		fmt.Printf("y shape: %v, yRef shape: %v\n", y.Shape().Dims(), yRef.Shape().Dims())
		fmt.Printf("max_abs_diff y: %.6g\n", maxAbsDiff(y.Data(), yRef.Data()))
	}
	if dx == nil {
		fmt.Println("dx is nil (x not marked as variable?)")
	} else {
		fmt.Printf("dx shape: %v, dxRef shape: %v\n", dx.Shape().Dims(), dxRef.Shape().Dims())
		fmt.Printf("max_abs_diff dx: %.6g\n", maxAbsDiff(dx.Data(), dxRef.Data()))
	}
}
